#!/usr/bin/env bash
# dev.sh — documents the two-terminal startup for Lume
# Does not background processes — run each block in a separate terminal.

echo "=== Lume Development Startup ==="
echo ""
echo "Terminal 1 — Backend:"
echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
echo "  cd services/typo"
echo "  uv run uvicorn app.main:app --reload --port 8000"
echo ""
echo "Terminal 2 — Frontend:"
echo "  cd apps/web"
echo "  pnpm dev"
echo ""
echo "Then open: http://localhost:3000"
echo ""
echo "Port conflict? Try:"
echo "  lsof -i :3000   # find frontend conflict"
echo "  lsof -i :8000   # find backend conflict"
echo "  PORT=3001 pnpm dev   # frontend fallback"
echo "  uv run uvicorn app.main:app --port 8001   # backend fallback (update .env)"
echo ""
echo "To reset the database:"
echo "  python scripts/reset_db.py"
echo ""
echo "To collect real-user data:"
echo "  # Stop uvicorn first, then:"
echo "  export LUME_COLLECT_MODE=real_user"
echo "  cd services/typo && uv run uvicorn app.main:app --reload --port 8000"
